### ISSUE TITLE
Hotswap attempts to read/compile source map (".js.map") files

### ISSUE THREAD

**Issue by laurence-myers** [rlidwka/node-hotswap#6]
My web application is written in TypeScript. Hotswap is used to swap out the generated JS on the app server. If I generate source maps as well as JS, it looks like Hotswap attempts to read/compile the source map files.

I've played with the configuration but couldn't work out a way to exclude ".js.map" files from hotswap.

Could I be doing something odd in my imports/requires to trigger this behaviour?

Example stack trace:

```
debugger listening on port 5858
NODE_ENV: development

/Users/laurence/digitalstack/generated/server/models/db/AccessToken.js.map:1
ction (exports, require, module, __filename, __dirname) { {"version":3,"file":
                                                                    ^
SyntaxError: Unexpected token :
    at Module._compile (module.js:439:25)
    at extension_js (/Users/laurence/digitalstack/node_modules/hotswap/hotswap.js:220:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at module.exports.Sequelize.import (/Users/laurence/digitalstack/node_modules/sequelize/lib/sequelize.js:621:63)
    at /Users/laurence/digitalstack/generated/server/models/db/index.js:29:44
    at Array.forEach (native)
    at new DbContainer (/Users/laurence/digitalstack/generated/server/models/db/index.js:28:14)
    at Object.<anonymous> (/Users/laurence/digitalstack/generated/server/models/db/index.js:43:10)
    at Module._compile (module.js:456:26)
    at extension_js (/Users/laurence/digitalstack/node_modules/hotswap/hotswap.js:220:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
```

**Comment by laurence-myers** [comment]
Nope, completely unrelated to hotswap! I must have been confused by seeing it in the stacktrace.

(I had some code that was dynamically importing module files without checking they ended in ".js".)
